"""add Department

Revision ID: 303a6ed64c2c
Revises: 99d19f3aef34
Create Date: 2026-01-03 22:26:51.499153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303a6ed64c2c'
down_revision = '99d19f3aef34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
